### ISSUE TITLE
Probleme mit der Installation

### ISSUE THREAD

**Issue by cinziaaeberhard** [contao-themes-net/mate-isotope-bundle#2]
Hallo, wir wollten gerade den Mate Isotop Shop installieren und scheitern schon an Schritt 1. "Ersetze die Domain und das Passwort."
Welches Passwort sollen wir da eingeben? Unten in der Vorschau steht dann Benutzername, statt Domain. Also was soll das wirklich rein? 
"url": "https://BENUTZERNAME:PASSWORT@packages.contao.store"

**Comment by MDevster** [comment]
Hallo @cinziaaeberhard bitte poste keine Zugänge hier auf Github. Bitte ändere dein Passwort so schnell wie möglich! Du hast eben eine E-Mail mit dem Zugang erhalten.
