### ISSUE TITLE
Compatibility Contao 5.* / MATE 3.*

### ISSUE THREAD

**Issue by DrAColian** [contao-themes-net/mate-isotope-bundle#5]
Hi,

is there any new version that is working with MATE Theme 3.* (and Contao 5.*)? I can only install 1.2.0, and this one is not working with a Contao update.

Thanks and kind regards
Dr.A.Colian

**Comment by MDevster** [comment]
Hi, Isotope is currently not available for Contao 5. You have to use Contao 4.13 instead. See https://github.com/isotope/core/blob/2.8/composer.json#L37

You can find more information about the update to Contao 5 in our blog  https://pdir.de/news/warum-sollte-ich-bereits-contao-5-0-einsetzen.html
